### PR TITLE
Allow disabling retries via Client.DisableRetries

### PR DESCRIPTION
**Pull request by nickatsegment**
Because I was in here already. The new default behaviour will be the current behaviour (i.e., do do retries)

https://github.com/segmentio/terraform-enterprise-go/issues/9

### CODE REVIEW

**Comment by systemizer** [comment]
What's the case in which we wouldn't want to retry?

**Comment by nickatsegment** [comment]
@systemizer I was thinking we could push the retry logic up to the caller, as per https://github.com/segmentio/terraform-enterprise-go/issues/9. The caller could supply a custom http.Client that does retries

**Comment by systemizer** [comment]
ah ok. IMO, if we're choose to do retries in this library then the user of the library shouldn't feel like they need to implement custom retry logic to the http client (at least I can't see why yet).

If we want to do retries in the http client, we could initialize the default client with a http client that does retries and then just delete the retry logic in the library. The one gotcha with this is that if someone wants to use a custom HTTP client, they will need to make sure their client also does retries

**Comment by nickatsegment** [comment]
> If we want to do retries in the http client, we could initialize the default client with a http client that does retries and then just delete the retry logic in the library

Yep, I agree this is probably the best way to go. But as it stands, this pkg has no deps except stdlib, which is kind of nice.

Oh, maybe you're saying we could move the retry logic into an http.Client (like a retryablehttp-lite) and use that as the default? That would work and would avoid external deps. 👍

**Comment by systemizer** [comment]
Either way. Id still argue that users of the library shouldn't have to implement their own retry logic, and instead that should be done by the library. Whether the library does that in the http client or within the code itself, I'm indifferent

**Comment by nickatsegment** [comment]
I went ahead and put an interface in the middle, got it all working, then realized that interface isn't actually compatible with `retryablehttp.Client`, because they use their own custom `Request` type, used by `Do`. I think instead the interface should be `Get`, `Post`, etc.

But for now I'm done with this experiment. Really, I'm thinking we just should use and vendor retryablehttp.

**Comment by systemizer** [comment]
ah :/ 

im for vendoring retryablehttp

**Comment by nickatsegment** [comment]
Oh, actually, using retryablehttp would break `NewWithClient`, or require a bunch of work to support either an http.Client or retryablehttp.Client.

I think we only use GET, and both Get methods are the same. Maybe that's the correct interface.

**Pull request closed without merging**
